import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import Hero from "@/sections/Hero";
import Features from "@/sections/features";

import {ReactLenis} from "@/utils/lenis"

const fontSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SaaS Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis root options={{
        lerp: 0.07
      }}>
        <body className={`${fontSans.variable} scroll-smooth`}>
          <Header />
          <Hero />
          <Features />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
