import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import Hero from "@/sections/Hero";
import Features from "@/sections/Features";
import Pricing from "@/sections/Pricing";
import Faq from "@/sections/Faq";

import { ReactLenis } from "@/utils/lenis";

const fontSans = Plus_Jakarta_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SaaS Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis
        root
        options={{
          lerp: 0.07,
        }}
      >
        <body className={`${fontSans.variable} scroll-smooth overflow-hidden`}>
          <Header />
          <Hero />
          <Features />
          <Pricing />
          <Faq />
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
